//! Wire types for the InfiniteCode-compatible HTTP coordination layer.
//!
//! The HTTP layer is transport-neutral and intentionally mirrors the shape of
//! the InfiniteCode / Codebuff coordination API so that the same client SDKs work
//! against either backend. The agent stays client-side (InfiniteCode's runtime
//! is the same Rust code; only the coordination endpoints differ).
//!
//! These types are the source of truth for the JSON shapes exchanged with
//! `/api/v1/infinitecode/session`, `/api/v1/web-search`, `/api/v1/docs-search`,
//! `/api/v1/gravity-index`, `/api/v1/token-count`, `/api/v1/ads/*`, and the
//! auth / healthz shim. They are deliberately a small, self-contained subset;
//! see `crate::http` for the handler wiring.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use smol_str::SmolStr;

/// Status of a coordination session, mirrored from the InfiniteCode-side enum
/// (`none | active | ended | superseded | country_blocked | banned |
/// rate_limited | takeover_prompt`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CoordinationSessionStatus {
    /// Initial get is in-flight. Should resolve quickly; clients should poll.
    None,
    /// Session is admitted and active; the assigned model is live.
    Active,
    /// Session has been released by the client (DELETE /api/v1/infinitecode/session) or
    /// its grace period has elapsed. The model may still be finishing work on
    /// the agent side; this is informational only and not an error.
    Ended,
    /// Another client POSTed a new session for the same acting user id. The
    /// previous session is replaced; subsequent GETs on the old instance id
    /// should transition to "Superseded" UI state.
    Superseded,
    /// The requesting IP / country is outside the supported free-tier region.
    /// Terminal for the session — clients show the geofence screen.
    CountryBlocked,
    /// The acting user id is banned. Terminal.
    Banned,
    /// The acting user id hit a shared quota (e.g. premium model daily cap).
    /// Terminal for this tab — user can retry on a different model.
    RateLimited,
    /// Another local InfiniteCode CLI / Desktop instance already holds this
    /// acting user id and refused to be supplanted. Terminal.
    TakeoverPrompt,
}

/// Concurrency bucket the model occupies, mirrored from
/// `occupyInfiniteCodeDesktopSlot`. Controls whether the user can run another
/// premium-bucket tab concurrently.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CoordinationSessionBucket {
    /// Premium bucket (DeepSeek V4 Pro, MiMo 2.5 Pro, Kimi K2.7 Code, HY3,
    /// KAT Coder Pro V2, MiniMax M3, GLM 5.2 — one per user at a time).
    Premium,
    /// Unlimited bucket (DeepSeek V4 Flash, MiMo 2.5 — no concurrency cap).
    Unlimited,
    /// Limited-access tier (every model into the single slot; one tab only).
    Limited,
}

/// Body of `POST /api/v1/infinitecode/session`.
///
/// The acting user id is required and is the rotation key: a new POST for the
/// same acting user id supersedes any prior active session for that user.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct CoordinationSessionRequest {
    /// Stable per-instance id generated by the client (typically a UUID). This
    /// is what the client polls in `GET /api/v1/infinitecode/session/:instance_id`
    /// and what headers carry (`x-infinitecode-instance-id`).
    pub instance_id: SmolStr,
    /// Stable per-user id from the auth login flow. Two sessions sharing this
    /// key will compete — only the most recent survives.
    pub acting_user_id: SmolStr,
    /// Model slug the client wants to use (e.g. `deepseek/deepseek-v4-pro`).
    pub model: SmolStr,
    /// Region / country ISO code; used by the country_blocked gate.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iso_country_code: Option<SmolStr>,
    /// Stable device fingerprint hash for session-management.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_fingerprint: Option<SmolStr>,
    /// App version, surfaced in audit logs.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub app_version: Option<SmolStr>,
}

/// Body of `GET /api/v1/infinitecode/session` and the response of `POST`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct CoordinationSessionResponse {
    pub instance_id: SmolStr,
    pub status: CoordinationSessionStatus,
    pub model: SmolStr,
    pub bucket: CoordinationSessionBucket,
    /// Remaining wall-clock time until the session expires, milliseconds.
    /// `None` when the session is not active.
    pub time_remaining_ms: Option<i64>,
    /// Server-assigned session start time, ISO-8601 UTC.
    pub started_at: DateTime<Utc>,
    /// Server-assigned session expiry when the session is finite, ISO-8601
    /// UTC. `None` represents "no fixed end" (chat-only ad-hoc poster).
    pub expires_at: Option<DateTime<Utc>>,
    /// Stable opaque reason string for terminal statuses (e.g.
    /// `'shared_premium_quota'`, `'cn_geofence'`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<SmolStr>,
    /// Seconds until the user's shared daily quota resets (Pacific time).
    /// `None` if not applicable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_quota_reset_secs: Option<i64>,
}

/// `POST /api/v1/web-search` proxy request.
///
/// The server forwards this to a Serper-shaped upstream and normalises the
/// response into a single `result` string for the agent.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct WebSearchRequest {
    pub query: SmolStr,
    #[serde(default = "default_search_depth")]
    pub depth: WebSearchDepth,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub repo_url: Option<SmolStr>,
}

fn default_search_depth() -> WebSearchDepth {
    WebSearchDepth::Standard
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WebSearchDepth {
    Standard,
    Deep,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct WebSearchResponse {
    pub result: SmolStr,
    #[serde(default)]
    pub credits_used: u64,
}

/// `POST /api/v1/docs-search` proxy request.
///
/// Resolved via Context7-shaped upstream into a markdown string.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct DocsSearchRequest {
    pub library_title: SmolStr,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub topic: Option<SmolStr>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub repo_url: Option<SmolStr>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct DocsSearchResponse {
    pub documentation: SmolStr,
    #[serde(default)]
    pub credits_used: u64,
}

/// `POST /api/v1/gravity-index` proxy request: third-party developer service
/// discovery (databases, AI APIs, payments, hosting, ...).
///
/// `mode` decides the operation:
///   - `Search` → search the index (`input.query`).
///   - `Browse` → paginated list of services (`input.category`, `input.cursor`).
///   - `ListCategories` → enumerate categories (`input` empty).
///   - `GetService` → fetch one service (`input.service_id`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GravityIndexOperation {
    Search,
    Browse,
    ListCategories,
    GetService,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct GravityIndexRequest {
    pub mode: GravityIndexOperation,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub query: Option<SmolStr>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub category: Option<SmolStr>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<SmolStr>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_id: Option<SmolStr>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct GravityIndexResponse {
    /// Loose JSON object specific to the operation (search hits, browse
    /// pagination tokens, category list, or one service descriptor).
    pub payload: serde_json::Value,
    #[serde(default)]
    pub credits_used: u64,
}

/// `POST /api/v1/token-count` proxy request — backed by Anthropic
/// `count_tokens` so reports include exact prompt-cache math. Heavier HTTP
/// traffic; free mode should fall back to the local token estimate instead.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct TokenCountRequest {
    /// Messages as Prometheus Messages; same shape as Anthropic accepts.
    pub messages: serde_json::Value,
    /// Optional system prompt, Anthropic-shaped.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub system: Option<serde_json::Value>,
    /// Model id used for context-cache accounting; not used to infer billing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<SmolStr>,
    /// Optional tool descriptor list to include in the count.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tools: Option<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct TokenCountResponse {
    pub input_tokens: u64,
    /// Mirrors Anthropic's `cache_creation_input_tokens` when the upstream
    /// returns them.
    #[serde(default)]
    pub cache_creation_input_tokens: u64,
    /// Mirrors Anthropic's `cache_read_input_tokens` when the upstream
    /// returns them.
    #[serde(default)]
    pub cache_read_input_tokens: u64,
}

/// `POST /api/v1/ads` auction request.
///
/// The runtime sends a JSON-RPC envelope, the response includes the auction
/// outcome (or `auction: null` if there is no ad for this surface).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct AdAuctionRequest {
    pub placement: AdPlacement,
    /// Conversation-message context the auction may use for targeting.
    #[serde(default)]
    pub messages: Vec<serde_json::Value>,
    /// Stable opaque session id from `x-infinitecode-instance-id`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<SmolStr>,
    /// Stable device fingerprint hash, used for fraud scoring.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device: Option<SmolStr>,
    /// User agent for placement rules. We deliberately spoof Chrome UA per the
    /// desktop ad client to avoid edge-case ad-server quirks.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<SmolStr>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum AdPlacement {
    DesktopInlineChat,
    DesktopBelowChat,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct AdAuctionResponse {
    /// `None` when no ad is served on this surface for this request.
    pub auction: Option<AuctionedAd>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct AuctionedAd {
    pub ad_id: SmolStr,
    pub creative_url: SmolStr,
    pub headline: SmolStr,
    pub body: SmolStr,
    /// Click-tracked URL. The client opens this on user click and posts
    /// `POST /api/v1/ads/click { ad_id }` separately.
    pub click_url: SmolStr,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct AdImpressionRequest {
    pub ad_id: SmolStr,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<SmolStr>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct AdClickRequest {
    pub ad_id: SmolStr,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<SmolStr>,
}

/// Auth shim.
///
/// `POST /api/v1/auth/login` takes a configured password (operator supplies
/// via `[infinitecode_bridge].password` in `config.toml` or
/// `INFINITECODE_BRIDGE_PASSWORD` env override) and mints a
/// long-lived bearer token. Subsequent endpoints validate against the same
/// shared secret.
///
/// The shim is intentionally minimal: the agent's own auth lives in
/// NextAuth; this layer is for the coordination API only.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct AuthLoginRequest {
    pub password: SmolStr,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct AuthLoginResponse {
    pub token: SmolStr,
    /// Unix epoch seconds until token expiry (24h by default).
    pub expires_at: i64,
}

/// `GET /api/healthz` response.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct HealthzResponse {
    pub status: SmolStr,
    pub version: SmolStr,
    pub uptime_secs: u64,
}

/// JSON-RPC 2.0 error envelope mirrored from the InfiniteCode-side response
/// shape so clients can reuse the same parser.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct CoordinationErrorBody {
    pub code: i32,
    pub message: SmolStr,
    /// Optional machine-readable status discriminator (e.g. `superseded`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<SmolStr>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<SmolStr>,
}

impl CoordinationErrorBody {
    /// A short, stable numeric error code. Mirrored from the InfiniteCode-side
    /// `AcpErrorCode`-shaped enum.
    pub const SESSION_SUPERSEDED: i32 = 409_001;
    pub const SESSION_RATE_LIMITED: i32 = 429_001;
    pub const SESSION_COUNTRY_BLOCKED: i32 = 451_001;
    pub const AUTH_REQUIRED: i32 = 401_000;
    pub const AUTH_INVALID: i32 = 401_001;
    pub const BAD_REQUEST: i32 = 400_000;
    pub const INTERNAL: i32 = 500_000;
    pub const NOT_IMPLEMENTED: i32 = 501_001;
}
