// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderRetryPhase } from "./ProviderRetryPhase";

export type TurnProviderRetryStatusPayload = { session_id: SessionId, turn_id: TurnId, attempt: number, backoff_ms: bigint, provider: string, model: string, phase: ProviderRetryPhase, message: string, };
